# Generated by Django 4.2.7 on 2023-12-06 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.SlugField(max_length=250)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee_fabrication', models.DateField()),
                ('couleur', models.CharField(max_length=50)),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Dis', 'Disponible'), ('InDis', 'IndDisponible')], default='Dis', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-annee_fabrication', 'marque', 'modele'],
            },
        ),
        migrations.CreateModel(
            name='VoitureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesVoiture', to='locations_voitures.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('mise_ajour_date', models.DateTimeField(auto_now=True)),
                ('date_fin', models.DateField()),
                ('nombres_jours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations_voitures.voiture')),
            ],
        ),
    ]
